
module: KituraOpenAPI
author: IBM & Kitura Project Contributors
github_url: https://github.com/Kitura/Kitura-OpenAPI

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, KituraOpenAPI.xcodeproj, -target, KituraOpenAPI, LIBRARY_SEARCH_PATHS=.build/debug]
